# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0e\x41\x63\x63ountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"K\n\x0f\x41\x63\x63ountResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63lient\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\"D\n\x14\x43reateAccountRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\"P\n\x14UpdateAccountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63lient\x18\x02 \x01(\x05\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\"L\n\x10SendMoneyRequest\x12\x14\n\x0c\x66rom_account\x18\x01 \x01(\x05\x12\x12\n\nto_account\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"n\n\x13TransactionResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x66rom_account\x18\x02 \x01(\x05\x12\x12\n\nto_account\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xc7\x04\n\x0e\x41\x63\x63ountService\x12?\n\nGetAccount\x12\x17.account.AccountRequest\x1a\x18.account.AccountResponse\x12G\n\x12GetAccountByClient\x12\x17.account.AccountRequest\x1a\x18.account.AccountResponse\x12\x42\n\x0cListAccounts\x12\x16.google.protobuf.Empty\x1a\x18.account.AccountResponse0\x01\x12H\n\rCreateAccount\x12\x1d.account.CreateAccountRequest\x1a\x18.account.AccountResponse\x12H\n\rUpdateAccount\x12\x1d.account.UpdateAccountRequest\x1a\x18.account.AccountResponse\x12@\n\rDeleteAccount\x12\x17.account.AccountRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\tSendMoney\x12\x19.account.SendMoneyRequest\x1a\x1c.account.TransactionResponse\x12K\n\x10ListTransactions\x12\x17.account.AccountRequest\x1a\x1c.account.TransactionResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=55
  _globals['_ACCOUNTREQUEST']._serialized_end=83
  _globals['_ACCOUNTRESPONSE']._serialized_start=85
  _globals['_ACCOUNTRESPONSE']._serialized_end=160
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=162
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=230
  _globals['_UPDATEACCOUNTREQUEST']._serialized_start=232
  _globals['_UPDATEACCOUNTREQUEST']._serialized_end=312
  _globals['_SENDMONEYREQUEST']._serialized_start=314
  _globals['_SENDMONEYREQUEST']._serialized_end=390
  _globals['_TRANSACTIONRESPONSE']._serialized_start=392
  _globals['_TRANSACTIONRESPONSE']._serialized_end=502
  _globals['_ACCOUNTSERVICE']._serialized_start=505
  _globals['_ACCOUNTSERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
